- id: stylus-supremacy
  name: 'Stylus Supremacy'
  description: 'Format Stylus files'
  language: node
  types: [stylus]
  additional_dependencies: ['stylus-supremacy@4.0.0']
  entry: 'stylus-supremacy format --replace'