on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --ignore-scripts

      - run: npx make-next-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
